eureka:
  client:
    serviceUrl:
      defaultZone: 
server:
  port: 8099
  servlet:
    context-path: /amq
spring:
  activemq:
    broker-url: tcp://47.97.188.93:61616
    password: 
    pool:
      enabled: true
      max-connections: 100
    user: 
  application:
    name: amq-server

